FROM p4-hdfs
CMD ["sh", "-c", "export CLASSPATH=$HADOOP_HOME/bin/hdfs:$(hdfs classpath --glob) && hdfs namenode -format && hdfs namenode -D dfs.namenode.stale.datanode.interval=10000 -D dfs.namenode.heartbeat.recheck-interval=30000 -fs hdfs://boss:9000"]
