FROM mysql:8.4.0-oraclelinux8

WORKDIR /
#COPY init.sql /docker-entrypoint-initdb.d/
COPY hdma-wi-2021.sql.gz /docker-entrypoint-initdb.d/
RUN gzip -d /docker-entrypoint-initdb.d/hdma-wi-2021.sql.gz
CMD ["mysqld"]

